### ISSUE TITLE
Instagramor Widget Logo

### ISSUE THREAD

**Issue by apocsantos** [scottsweb/wp-instagram-widget#111]
Hi,
I've been strugling a bit trying to mess with the code in order to get the widget logo on top near the "Title". It would be nice to have it as it would be more appealing to end users.

**Comment by scottsweb** [comment]
Can you let me know what you mean by 'widget logo'. Are you trying to add the Instagram logo to your site? If so, that should be possible with CSS.

**Comment by apocsantos** [comment]
Exactly the Instagram Logo, near the title of the widget.

**Comment by scottsweb** [comment]
This should be possible with custom CSS:

```CSS
.null-instagram-feed .widget-title {
    background-image: url('....
}
````
